### PR TITLE
fix: add support to inlined functions + sparkplug on v16+

### PR DESCRIPTION
**Pull request by RafaelGSS**
I'm still looking if there is something missing because looks like the call stack are not completely correct. 

By the way, I'm running this fork: https://github.com/RafaelGSS/slow-rest-api

```console
node ../node-clinic/bin.js flame --on-port='npm run test' -- node index.js
```

and I'm getting the graph attached

image

Look that `payload` function is side by side of `a`/`b`/`c`/ function which is its caller

image

Does that is acceptable? @mcollina

[204430.clinic-flame.zip](https://github.com/davidmarkclements/0x/files/7945683/204430.clinic-flame.zip)

### CODE REVIEW

**Comment by RafaelGSS** [comment]
Well, looks like it still happens even before my fix (which is unrelated to that). So, it's ready to go.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by RafaelGSS** [comment]
I did a second deeper look at it and looks good. Unfortunately, `inlined` functions are usually skipped from call-stack: https://github.com/davidmarkclements/0x/blob/master/lib/ticks-to-tree.js#L118

but this is a different issue, I think that it could land. Would you mind merging?

**Comment by mcollina** [comment]
should I release or would you like to fix the other problem too?

**Pull request merged**
