### PR TITLE
Remove load phase

### PR DESCRIPTION
**Pull request by BridgeAR**
Slow rest api:

Node master with init:
image

Node master without init:
image

Node 10.9 without init:
image

Node 8.12 without init:
image

Some util inspect code:

Node master with init:
image

Node master without:
image

Node 10.9 with init:
image

Node 10.9 without init:
image

Node 8.12 without init:
image

### CODE REVIEW

**Comment by BridgeAR** [comment]
I described how everything works in the description and the code comments. I hope that everything is understandable.

**Comment by BridgeAR** [comment]
I missed to add two new files

**Comment by BridgeAR** [comment]
:/

**Comment by mcollina** [comment]
push them to master directly

**Comment by BridgeAR** [comment]
I have no commit rights

**Pull request merged**
