### PR TITLE
linux: fixes perf profiling stacktraces

### PR DESCRIPTION
**Pull request by RafaelGSS**
Address: #242 

This PR also adds support to categorization through perf stack traces.

### CODE REVIEW

**Comment by RafaelGSS** [comment]
Quick feedback. I'm still working in the PR because it's missing:

- A better parser of functions with categories (CPP, V8, JS)

image

- Inlined functions

**Comment by RafaelGSS** [comment]
While I look into how to test those changes, this PR is ready to review.

**Comment by RafaelGSS** [comment]
The 0x now creates a flamegraph like this one:

image

(It was not even generated in the master version)

---

Also, notice that `^etag.js` and `etag.js` are considered different stack-line, someone knows why?

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
