### PR TITLE
feature: electron, initial stab

### PR DESCRIPTION
**Pull request by eljefedelrodeodeljefe**
See https://www.youtube.com/watch?v=F7zGclpMXkA

Handles also people not wanting to install electron by `NO_OPEN_0X=true` environment variable and conditional, programmatic `npm install` via `preinstall` hook.

Was a quick one, but I think it is extensible.

### CODE REVIEW

**Comment by mcollina** [comment]
So I think we can make the process interactive: the user launch 0x, and if it _thinks_ it should open electron, it will ask the end user and then it will start the download of prebuilt. I would use the same process https://www.npmjs.com/package/insight uses to remember the choice.

We can possibly detect if we can open a desktop app by looking at some env variable.

BTW, we should add insight as well.

**Comment by davidmarkclements** [comment]
@eljefedelrodeodeljefe nice touch with the icon 😋 

@mcollina @eljefedelrodeodeljefe I'm not sure this should be part of 0x (as per https://github.com/davidmarkclements/0x/issues/30#issuecomment-211340639) but rather a separate module - this side-steps the whole download prebuilt if config specifies to use 0x

at any rate we can always pull it out if need be and work backwards with the `open` flag

next steps is to integrate file viewing - I'm thinking we pass a "view" opt, which is a function that gets called when the user (double clicks? cmd clicks? 1st click widens, 2nd click views?) on a frame

It would be real nice if the user could associate a view command - e.g. `vi` of `subl` etc. etc. could default to `$EDITOR` env var.

At the same time, a preview popout box could open (on hover?) at the particular line, with 2-3 surrounding lines above and beneath 

ref: #30

**Comment by eljefedelrodeodeljefe** [comment]
Hmm okay. I'll continue, but it's going to be harder with the option passing in to another module. But why not. 

I am already including the CLI prompt as @mcollina suggested. That would probably need to stay in this module as well as well as the option persisting.

I'll send in new stuff later.

**Comment by eljefedelrodeodeljefe** [comment]
@davidmarkclements this turns out to be a bigger problem. We would need the process.kill / process.on('exit') refactoring I was proposing unfortunately. Process.on('exit') allows only synchronous function calls in the handler. Most of the interactive logic (and in the feature other probably as well) is async. 

Can you decide on this quickly so I can do it right away? Otherwise we cannot have the conditional install logic in the app.

**Comment by davidmarkclements** [comment]
hey @eljefedelrodeodeljefe sorry for not getting back sooner - 

I think the approach as it stands is too coupled - what I'd rather see is an independent command being executed on process.exit (btw, love your thinking on passing path through process.exit, never would have thought of that) 

So 0x-view should have it's own bin - rather than be required in.

Advantages are

1. if we decide to go with the conditional install or prebuilt, the separate bin can handle that
2. the bin command can be easily configured via an open flag (e.g. you could set it to chrome etc.)
3. it makes it v. easy to extract into it's own module later

We also need to take out the NO_0X_VIEW thing out, first I'm not sure 0x-view should be default, and at any rate it doesn't cater to people who are including 0x via package deps, potentially as part of a build process (like @yoshuawuyts)

**Comment by davidmarkclements** [comment]
hey @eljefedelrodeodeljefe we can talk more about this offline - I think this should be a separate project

**Comment by eljefedelrodeodeljefe** [comment]
Yep. Like the idea.

**Pull request closed without merging**
