### PR TITLE
More contrasted colors

### PR DESCRIPTION
**Pull request by mcollina**
schermata 2017-09-26 alle 19 17 56

and B&W (to see the contrast)

schermata 2017-09-26 alle 18 56 41

I have also fixed some layout issues.

### CODE REVIEW

**Comment by davidmarkclements** [comment]
yeah that's real nice

what does it look like on black bg? 

I'm happy to set default to white bg btw if this is acceptable in black but looks better on white (esp projectors etc)

**Comment by mcollina** [comment]
schermata 2017-09-27 alle 09 32 22

Black background

**Comment by davidmarkclements** [comment]
let's make the default bg white

**Comment by mcollina** [comment]
schermata 2017-09-27 alle 11 41 41

I've added a legenda at the top and fixed a couple more issues.

**Comment by davidmarkclements** [comment]
amazing, thank you @mcollina

**Pull request merged**
