### PR TITLE
Do not require pathToNodeBinary to be set

### PR DESCRIPTION
**Pull request by BridgeAR**
This was the case when 0x was used in a programatic way.

### CODE REVIEW

**Comment by AlanSl** [comment]
Still getting the error when using this branch in Clinic Flame. Source of error is index.js:107 `await v8LogToTicks(src, pathToNodeBinary)`, we should apply fallback in the `visualize` function too.

Might be other places also.

**Comment by AlanSl** [comment]
`...name, pathToNodeBinary = process.execPath })` in `visualize` function arguments seems to fix flame private master.

**Comment by BridgeAR** [comment]
@AlanSl please check again. This should fix it.

**Comment by AlanSl** [comment]
LGTM. Fixes both public and private and is much cleaner than my suggestion.

**Pull request merged**
