### PR TITLE
pass command line arguments through to spawned process

### PR DESCRIPTION
**Pull request by rwallace-kabam**
I didn't make the corresponding linux change because I'm not currently set up to test it.  It would be the same simple concatenation.

Also added restify dependency

https://github.com/davidmarkclements/0x/issues/70

### CODE REVIEW

**Comment by rwallace-kabam** [comment]
Someone who's well set up to test linux should probably make the corresponding change - just concatenating the script_args in the call to spawn.  I didn't want to tie it up in this PR since I can't test it.

**Comment by davidmarkclements** [comment]
0x ... doesn't depend on restify 

There might be an example folder with restify with its own package.json which should have restify as a dependency - but 0x itself has no need for restify

Regarding script args this used to work, @mcollina did that previous PR that required addition of node_options flag also break script flags?

**Comment by mcollina** [comment]
Possibly! @rwallace-kabam can you please provide an example that is broken?

**Comment by rwallace-kabam** [comment]
@davidmarkclements yes, restify was only required for the example - my bad.

As for the script args, it looks like https://github.com/davidmarkclements/0x/issues/70 describes exactly what I was running into, and i found that his "alternate" solution including node in the call did not help.

To see a broken example, just `console.log(process.argv)` in examples/rest-api/index.js and run `0x examples/rest-api foo bar`.  See that `foo` `bar` are not passed through.

Also, thanks for the great talks and performance workshop at node interactive :)

**Comment by rwallace-kabam** [comment]
I've removed the commit adding restify as a dependency

**Comment by rwallace-kabam** [comment]
Pre-change:
screen shot 2017-10-06 at 5 13 07 pm

Post-change:
screen shot 2017-10-06 at 5 14 21 pm

**Pull request merged**
